### ISSUE TITLE
Lot of delay in status, locking, doorbell ding sensor

### ISSUE THREAD

**Issue by ghost** [snjoetw/py-august#9] opened 2018-10-01 12:50 UTC
It takes sometimes upwards of 45 seconds for the doorbell to trigger status and hence automation.
Same with locking and unlocking and status of door lock.
Is there a way I can change this?
Am I doing something wrong?
Thanks

**Comment by forums2012** [comment] 2018-10-01 22:07
Lot of messages similar to this in log:
Updating august lock took longer than the scheduled...

**Comment by ehendrix23** [comment] 2018-10-23 21:06
@ghost

I just created PR https://github.com/snjoetw/py-august/pull/11 that might (or might not) alleviate part of this problem.

I'm assuming this is from HASS? How many doorbells do you have (assuming 1 but then again <g>). How many locks do you have?

There is a minimum of 5 seconds between updates.
There are 2 HTTPS call to August / lock for locks. 
There is 1 HTTPS call to August for a door sensor.
There is 1 HTTPS call to August for doorbells.
And then there is also 1 HTTPS call to retrieve house activities. This call can be initiated from either a lock or a doorbell update (but is only run once every 5 seconds maximum).

Currently during my testing, a call is about 300ms. This means that if you have 1 lock then the time to update is between 600ms and 900ms and a doorbell is between 300ms and 600ms (not including processing time but that should be minimal).

With this PR (and then another PR for HASS to enable sessions from there) that would be reduced on average to 110ms and 33ms for 1 lock and 55ms and 110ms for a doorbell. One of the main pieces with this PR is that once the session is established with the August web server it stays. This means no more negotiating on the certificate etc. (reduce back-and-forth traffic, and CPU time on both client and August web server).

Further, version 0.81 of HASS will include more debug logging from the August component in HASS. To enable, set the following in your configuration:
```
logger:
  default: warning
  logs:
    homeassistant.components.lock.august: debug
    homeassistant.components.binary_sensor.august: debug
    homeassistant.components.august: debug

```
Log entry of "Updating device activities" is when it retrieves the activities from August.

Log entry of "Start retrieving doorbell details" is the start to retrieve doorbell status with "Completed retrieving doorbell details" being the end (in between you should see entries "Updating status for <doorbell name>". The timing between those 2 will give you an idea on how long it took to perform the HTTPS calls.

Similar for "Start retrieving door status" and "Completed retrieving door status" as this is for the door sensor, lastly "Start retrieving locks status" and "Completed retrieving locks status" for lock status.

**Comment by 2016for** [comment] 2018-12-06 03:15
Amazing work.
However doesn't seem like the connectivity has improved for me.
And I have noticed that my doorbell ding sensor goes unavailable quite often now.
Will enable logger and send the debug messages.

Let's try to create a rock solid August component.


Recently worked with someone to get a websocket API running on HASS, is there a way we can figure out a websocket approach to interacting with August?

**Comment by ehendrix23** [comment] 2018-12-06 04:43
Send the debug messages. 

I haven’t had any issues with it once I implemented this. 
What version of HASS are you on?

**Comment by 2016for** [comment] 2018-12-06 13:18
I have 2 door locks (hence 2 door sensors), 1 doorbell

It seems like there's usually a 10-15 seconds delay for things to update on HA when I change locks either from August App or manually or the doorbell ringing (works pretty quick on Google Assistant though)

A few of these every now and then:

```
2018-12-06 15:15:41 WARNING (MainThread) [homeassistant.components.binary_sensor] Updating august binary_sensor took longer than the scheduled update interval 0:00:05
2018-12-06 15:15:41 WARNING (MainThread) [homeassistant.components.lock] Updating august lock took longer than the scheduled update interval 0:00:05
```

Lock errors:

`018-12-06 18:33:52 ERROR (SyncWorker_6) [homeassistant.components.august] Request error trying to retrieve door details for Side Door. HTTPSConnectionPool(host='api-production.august.com', port=443): Max retries exceeded with url: /locks/xxxxxxxxxxxxxxxxxxxx (Caused by SSLError(OSError(9, 'Bad file descriptor'),))`

August Camera Exceptions like this one:

```
018-12-06 15:05:58 DEBUG (SyncWorker_4) [homeassistant.components.august] Getting device activities
2018-12-06 15:06:02 ERROR (MainThread) [homeassistant.components.websocket_api.decorators] Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 301, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x6ec33b50>: Failed to establish a new connection: [Errno 101] Network unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='res.cloudinary.com', port=443): Max retries exceeded with url: /august-com/image/upload/xxxxxxxxxx/xxxxxxxxxxxxxxx.jpg (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at xxxxxxxxx>: Failed to establish a new connection: [Errno 101] Network unreachable',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/websocket_api/decorators.py", line 16, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/camera/__init__.py", line 463, in websocket_camera_thumbnail
    image = await async_get_image(hass, msg['entity_id'])
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/camera/__init__.py", line 93, in async_get_image
    image = await camera.async_camera_image()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/camera/august.py", line 74, in camera_image
    timeout=self._timeout).content
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='res.cloudinary.com', port=443): Max retries exceeded with url: /august-com/image/upload/xxxxxxxxx/xxxxxxxxxxxxx.jpg (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at xxxxxxxxxxx>: Failed to establish a new connection: [Errno 101] Network unreachable',))
```

The Doorbell ding & motion sensors somehow every day becomes unavailable quite often. However the Doorbell online sensor shows it was online throughout the night.

```
18-12-06 15:55:21 ERROR (MainThread) [homeassistant.helpers.entity] Update for binary_sensor.xxxxxxxx_ding fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 349, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/binary_sensor/august.py", line 183, in update
    self._state = state_provider(self._data, self._doorbell)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/binary_sensor/august.py", line 44, in _retrieve_ding_state
    [ActivityType.DOORBELL_DING])
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/binary_sensor/august.py", line 50, in _activity_time_based_state
    *activity_types)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/august.py", line 224, in get_latest_device_activity
    activities = self.get_device_activities(device_id, *activity_types)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/august.py", line 215, in get_device_activities
    self._update_device_activities()
  File "/usr/local/lib/python3.6/site-packages/homeassistant/util/__init__.py", line 324, in wrapper
    result = method(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/homeassistant/components/august.py", line 237, in _update_device_activities
    limit=limit)
  File "/usr/local/lib/python3.6/site-packages/august/api.py", line 188, in get_house_activities
    "limit": limit,
  File "/usr/local/lib/python3.6/site-packages/august/api.py", line 290, in _call_api
    self._http_session is not None else\
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
```

**Comment by 2016for** [comment] 2018-12-06 14:10
Again thanks a lot for the amazing work you're doing! 👍 

I definitely saw improvement over previous versions, earlier my log was filled with those updating took longer than expected errors.

Looking at the progress you have made so far, I am kind of getting over-ambitious to see it update insanely fast. :)

**Comment by ehendrix23** [comment] 2018-12-06 14:22
Hey,

Thank you. :-)

For the unavailable state. The entity will be set to unavailable when it fails to retrieve the updated data from August. 
Before the state would not change when there is an issue in connecting to August to get the data and in my opinion thus giving you the wrong impression. For example, you check if the door is locked and it states it is. In reality it isn't but we were unable to get the update state. Now, if we're unable to get the state then we set state to unavailable letting us know that in reality HASS has no clue right now what it is. :-)

I see quite a bit of "network unreachable" errors in there, together with what seems to be sockets being closed by the OS or so. What happens with having implemented sessions is that once the connection is made it is supposed to stay connected, and thus improving performance by not having to re-create the connection for every request.

I think here we need to figure out why you are getting the "network unreachable" errors however. What do you run HASS on? Are you on HASSIO, Raspberry Pi, Linux, Docker, Mac, Windows, ?

**Comment by 2016for** [comment] 2018-12-06 15:05
Thanks a lot for your response.

I am running Hassio 0.83.3 on Rpi2 connected via ethernet with reliable
internet connection with speeds of 150 mbps up and down.

**Comment by ehendrix23** [comment] 2018-12-06 20:07
OK,

Do you have any other items in HASS that need to retrieve data from something on the internet? And if so, do they have issues?

Would it be possible for you to initiate a regular ping to your RPi2 from something else? This to see if when you get these errors you also are unable to then ping your RPI2.
Further, would it be possible to initiate a ping from your RPi2 to res.cloudinary.com?

Here is a small test script that works on my Mac. You might need to modify a bit or so making it work on yours (I do not have a Raspberry to try).

```
#!/bin/bash

host=$1
port=$2
echo Pinging $1 till cancelled
while :;
 do
   if [ "${port}" != "" ]; then
      output=$(nc -w 1 $1 $2 </dev/null)
      rc=$?
   else 
      output=$(ping -c1 $host 2>&1)
      rc=$?
   fi
   if [ $rc -ne 0 ]; then
     echo $(date) $output
   fi
 done
```

What this does it it will keep on trying to ping the destination and anytime it fails will echo out the error with the timestamp. 
Might not be a bad idea either to have 2 running then. Maybe one going to res.cloudinary.com or api-production.august.com and one going to www.google.com or so.
Leave it running until you have at least had a few failures in HASS. Output will only be produced on failure.
Test out ensuring that on failure it fails by giving a bogus hostname or port. :-)

If you provide a port number then it will try using nc (which is just a tool trying to connect to a certain port on provided server).

If you provide just a hostname then it will use ping. If you provide hostname and port it will use nc.
For example:
`<script> res.cloudinary.com`
will do ping.
`<script> res.cloudinary.com 443`
will use nc going to port 443.

Trying to figure out why you're getting that network unreachable. And based on the log messages, it then also fails when it retries to connect. Hence I do not think there is much we can do on the development end when there is no network. :-)

Doing the above should at least be able to narrow it somewhat down if it is indeed a network issue or not.

**Comment by ehendrix23** [comment] 2018-12-06 23:22
What is the platform (or component) used for sonoff ewelink? Wanna check that code :-)

The August component in HASS needs to poll with the August servers, it does not get anything in. 
Not confirmed this, but it looks like this should be happening like every 5 seconds (I just confirmed on mine that it indeed checks every 5 seconds). Hence you will not be getting it any sooner then that. :-)

I also checked and I have not been getting any request errors since I put in the updated code with using sessions etc. unless I actually had a network problem. :-) This is for about a month now or so (as I was testing the updated code locally, then get the PR through for HASS, and then going into the release).

My doorbell sounds instantaneous within the house but never reflects in HASS, still using old-fashioned doorbell. :-) For August I just have 1 lock (with the door sensor).
I would say that the change I did with using sessions etc. would be even more advantageous as more items are added. 

Before the change, a lock without a door sensor would result in 2 requests / lock. If there was a door sensor as well it would result in 3 requests / lock. Now it is 2 requests / lock irrespective if there is a door sensor or not.

Before for each request a new connection would be made. Now the connection stays open and is re-used, not just for 1 update but even between updates.
So if you have 1 doorbell and 1 lock with sensor, before it would be doing 5 requests (there is also the device activity one) every 5 seconds, each time setting up the connection. 

Now it will be doing 4 requests and they will be leveraging connection(s) already setup. I for example have 2 connections setup and they stay around and thus re-used even between updates.

**Comment by 2016for** [comment] 2018-12-07 00:19
Check out the websocket branch of this:
http://github.com/peterbuga/HASS-sonoff-ewelink/blob/websocket/sonoff.py

**Comment by ehendrix23** [comment] 2018-12-07 00:44
Looking at the code, seems to me one of the big differences here is that Sonoff pushes changes and hence the listener. And thus also why using WebSockets.

So if something changes, a message is then send from Sonoff to the component. There is no need to poll. For August we do not have that luxury and we thus need to poll to get a state update.

**Comment by 2016for** [comment] 2018-12-07 09:30
True. But it seems like August might be pushing changes as well.
Because the doorbell notification (someone is ringing the doorbell) is near
instantaneous on Google Home.

This was recently added, required me to unlink and then relink August
account on Google Home.

So there's some hope there.

But I'm not able to leverage most out of the current code, so will send the
debug code soon. Thanks again for the help.

**Comment by 2016for** [comment] 2018-12-07 13:16
Will be sending you the debug log as soon as I can.

Read up on asyncio from your other posts and found a nice article on this:
https://terriblecode.com/blog/asynchronous-http-requests-in-python/

Do you think integrating this into this project or the HA project be of use?

**Comment by 2016for** [comment] 2018-12-07 13:39
Sorry for the constant bugging but I am really excited to make this as fast as possible.

Seems like August is using Async code to integrate with Alexa as well.

> Today, as an early adopter of the new Asynchronous Messaging, Proactive State Updates, and Capability Interfaces recently added to the Smart Home Skill API, August delivers a versatile, low-latency control and monitoring experience to Alexa customers

https://developer.amazon.com/blogs/alexa/post/7c9b3937-9f82-49fc-99dd-359d018fb25d/august-home-uses-smart-home-skill-api-for-faster-more-seamless-integration-of-locks-and-cameras

**Comment by ehendrix23** [comment] 2018-12-07 16:36
Reading this, what they seem to be saying is that before what had to happen was that when the action to unlock (or lock) was send from Alexa to August, August would not be allowed to respond back until it was done.
Now, Alexa is allowing a response back pretty much saying (working on it) and then once completed to say (done).
Further, as they state is that August sends state changes to Alexa (and pretty sure they do the same for Google Assistant). So it is not Alexa or GA polling August but rather August sending it to them.

How is this different? 
With polling:
   You lock the door -> Lock sends that it is locked to August servers
    Every 5 seconds poll August server to retrieve current state. Receive updated state.

With notification (August sending updates):
   You lock the door -> Lock sends that it is locked to August servers -> August sends to recipient that lock is locked

There is no polling. Like when you order a coffee. Polling is you on a regular basis going back to the counter and asking if your coffee is ready. Thus if you waited 2 minutes since the last time you asked, your coffee might have been sitting there for a minute.
With notifications it then is the barista telling you that your coffee is ready from the moment it is. Hence, you know immediately.

Until August provides us a method to connect to something and then allowing us to receive notifications on that channel we're going to have to do polling instead sadly enough. And that will always then come with a certain delay.

Now, the issue you are seeing however is due to something related to networking. I think if we can at least get that resolves so that you have a stable network connection then that should already help.

I also do not know how many devices you have in total, but I do have some ideas how it might be improved upon when there are multiple devices of the same type (probably mainly locks here as not sure how many doorbells one requires).

 I have a latency of 46ms to the August servers (this is important as higher latency means longer request times).
It takes about 593ms for 1 request if the connections has to be setup, about 166ms if the connection is already setup.

For each lock there are 2 requests, thus about 330ms if the connection exist or 780ms if 1st connection had to be setup.
If you have 10 locks then in reality it would take about 3 seconds to go through them. This happens for all the locks at once and hence nothing will be updated.

This probably can be improved upon potentially so that each lock will get it on their own instead of through 1 batch. 

I am working on another component right now. From the moment I am done with that one I'll come back to this one to see to change it to asyncio instead and then to improve the component in HASS itself.

**Comment by 2016for** [comment] 2019-01-13 09:02
Trying to figure out the problem still.
Seems like res.cloudinary.com & google.com are working properly (latency 70-80ms)
However ping api-production.august.com doesn't seem to respond.
What could be the problem?

Thanks again for all the help so far

**Comment by 2016for** [comment] 2019-01-13 09:03
Although the ping to api-production.august.com not working on my mac as well

**Closed** 2020-02-08 14:58 UTC
